name: Upload release assets

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Copy secrets
        run: |
          cd mobile
          echo '${{ secrets.GOOGLE_SERVICES }}' >> google-services.json
          echo {{ secrets.KEYSTORE_B64 }} | base64 -d | zcat >> essence-release.keystore
          echo {{ secrets.KEYSTORE_PROPS_B64 }} | base64 -d | zcat >> essence-release.properties
          cd ..
          cd wear
          echo '${{ secrets.GOOGLE_SERVICES }}' >> google-services.json
          echo {{ secrets.KEYSTORE_B64 }} | base64 -d | zcat >> essence-release.keystore
          echo {{ secrets.KEYSTORE_PROPS_B64 }} | base64 -d | zcat >> essence-release.properties
          cd ..
      - name: Build release version
        env:
          API_OPEN_WEATHER_MAP: ${{ secrets.API_OPEN_WEATHER_MAP }}
          API_ACCU_WEATHER: ${{ secrets.API_ACCU_WEATHER }}
          API_DARK_SKY: ${{ secrets.API_DARK_SKY }}
          API_WEATHER_STACK: ${{ secrets.API_WEATHER_STACK }}
        run: ./gradlew assembleRelease
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release "mobile.apk"
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mobile/build/outputs/apk/release/mobile-release.apk
          asset_name: essence-mobile-${{ github.ref }}.apk
          asset_content_type: application/zip
      - name: Upload release "wear.apk"
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: wear/build/outputs/apk/release/wear-release.apk
          asset_name: essence-wear-${{ github.ref }}.apk
          asset_content_type: application/zip
